### ISSUE TITLE
Missing dependencies in environment.yml

### ISSUE THREAD

**Issue by ghost** [alexander-n-thomas/spark-nlp-book#5]
When trying to install the conda environment for this package, I received two errors:

* As mentioned in issue #1 , R is not installed.
* There were also some missing header files from giflib that caused a CMake-based build to crash at some point.

**Comment by VyasKS** [comment]
![error](https://user-images.githubusercontent.com/39980005/105778757-47773200-5f6d-11eb-829b-a022eca606fb.png)
Following are the errors: Missing dependencies in the environment.yml
1. There is no R_HOME and the R executable cannot be found
2. ERROR: No matching distribution found for rpy2==3.2.7
    failed    
    CondaEnvException: Pip failed

**Comment by ghost** [comment]
Closing out, since no progress made.
